### ISSUE TITLE
github求助，急

### ISSUE THREAD

**Issue by einstein2023** [ibireme/ibireme.github.com#2]
你好，
https://github.com/sproutcui 账号转载了两个库都是我们的版权，希望您尽可能的联系他，并告之快速关闭；
联系您是因为在他的信息中，有关于您仓库的印记。

**Comment by xiaopinghuazai** [comment]
我不知道哦，我好久没用过github了密码都忘了。 不是我转载的吧。



在 2020-10-30 14:54:17，"einstein20050430" <notifications@github.com> 写道：

你好，
https://github.com/sproutcui 账号转载了两个库都是我们的版权，希望您尽可能的联系他，并告之快速关闭；
联系您是因为在他的信息中，有关于您仓库的印记。

**Comment by einstein2023** [comment]
close
